<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="29" time="0.465" timestamp="2025-10-20T18:04:48.310947-06:00" hostname="csci5840-vm3-prpr4002"><testcase classname="test_check_cpu" name="test_get_cpu_usage_success" time="0.002" /><testcase classname="test_check_cpu" name="test_get_cpu_usage_empty_output" time="0.001" /><testcase classname="test_check_cpu" name="test_get_cpu_usage_exception" time="0.001" /><testcase classname="test_check_cpu" name="test_main_high_cpu" time="0.001" /><testcase classname="test_check_cpu" name="test_main_normal_cpu" time="0.002" /><testcase classname="test_check_cpu" name="test_main_snmp_failure" time="0.001" /><testcase classname="test_device_health_check" name="test_find_credentials_success" time="0.002" /><testcase classname="test_device_health_check" name="test_find_credentials_not_found" time="0.004" /><testcase classname="test_device_health_check" name="test_find_credentials_file_not_found" time="0.001" /><testcase classname="test_device_health_check" name="test_check_ping_success" time="0.001" /><testcase classname="test_device_health_check" name="test_check_ping_failure" time="0.001" /><testcase classname="test_device_health_check" name="test_show_routes_and_neighbors_with_ospf" time="0.001" /><testcase classname="test_device_health_check" name="test_show_routes_and_neighbors_fallback" time="0.001" /><testcase classname="test_device_health_check" name="test_check_cpu_utilization_ok" time="0.001" /><testcase classname="test_device_health_check" name="test_check_cpu_utilization_high" time="0.001" /><testcase classname="test_device_health_check" name="test_check_cpu_utilization_parse_error" time="0.001" /><testcase classname="test_device_health_check" name="test_main_success" time="0.004" /><testcase classname="test_device_health_check" name="test_main_no_credentials" time="0.010"><failure message="AssertionError: Expected 'exit' to be called once. Called 2 times.&#10;Calls: [call(1), call(1)].">/home/student/lab1/pythonscripts/tests/test_device_health_check.py:149: in test_main_no_credentials
    mock_exit.assert_called_once_with(1)
/usr/lib/python3.12/unittest/mock.py:955: in assert_called_once_with
    raise AssertionError(msg)
E   AssertionError: Expected 'exit' to be called once. Called 2 times.
E   Calls: [call(1), call(1)].</failure></testcase><testcase classname="test_dynamic_ipam" name="test_read_device_passwords" time="0.003" /><testcase classname="test_dynamic_ipam" name="test_collect_ipam_success" time="0.006" /><testcase classname="test_dynamic_ipam" name="test_collect_ipam_connection_error" time="0.032" /><testcase classname="test_ping_test" name="test_load_devices_success" time="0.002" /><testcase classname="test_ping_test" name="test_get_device_type_cisco" time="0.000" /><testcase classname="test_ping_test" name="test_get_device_type_arista" time="0.000" /><testcase classname="test_ping_test" name="test_run_ping_success" time="0.001" /><testcase classname="test_ping_test" name="test_run_ping_failure" time="0.001" /><testcase classname="test_ping_test" name="test_run_ping_connection_error" time="0.001" /><testcase classname="test_ping_test" name="test_run_ping_skipped_device" time="0.000" /><testcase classname="test_ping_test" name="test_main" time="0.003" /></testsuite></testsuites>